interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "LICENSE",
    "build",
    "docs",
    "tests",
    "venv",
]
source_roots = [
    "sub-packages/bionemo-core/src",
    "sub-packages/bionemo-esm2/src",
    "sub-packages/bionemo-evo2/src",
    "sub-packages/bionemo-example_model/src",
    "sub-packages/bionemo-fw/src",
    "sub-packages/bionemo-geneformer/src",
    "sub-packages/bionemo-geometric/src",
    "sub-packages/bionemo-llm/src",
    "sub-packages/bionemo-scdl/src",
    "sub-packages/bionemo-size-aware-batching/src",
    "sub-packages/bionemo-testing/src",
    "sub-packages/bionemo-webdatamodule/src",
]

[[modules]]
path = "bionemo.core"
depends_on = []

[[modules]]
path = "bionemo.esm2"
depends_on = [
    "bionemo.core",
    "bionemo.llm",
]

[[modules]]
path = "bionemo.evo2"
depends_on = [
    "bionemo.noodles",
    "bionemo.core",
    "bionemo.llm",
]

[[modules]]
path = "bionemo.example_model"
depends_on = [
    "bionemo.core",
    "bionemo.llm",
]

[[modules]]
path = "bionemo.fw"
depends_on = [
    "bionemo.core",
    "bionemo.esm2",
    "bionemo.geneformer",
    "bionemo.geometric",
    "bionemo.llm",
    "bionemo.noodles",
    "bionemo.noodles",
    "bionemo.scdl",
    "bionemo.size_aware_batching",
    "bionemo.webdatamodule",
]

[[modules]]
path = "bionemo.geneformer"
depends_on = [
    "bionemo.core",
    "bionemo.llm",
    "bionemo.scdl",
]

[[modules]]
path = "bionemo.geometric"
depends_on = [
    "bionemo.core",
]

[[modules]]
path = "bionemo.llm"
depends_on = [
    "bionemo.core",
]

[[modules]]
path = "bionemo.noodles"
depends_on = [
    "bionemo.core",
]

[[modules]]
path = "bionemo.scdl"
depends_on = [
    "bionemo.core",
]

[[modules]]
path = "bionemo.size_aware_batching"
depends_on = [
    "bionemo.core",
]

[[modules]]
path = "bionemo.testing"
depends_on = [
    "bionemo.core",
    "bionemo.llm",
]

[[modules]]
path = "bionemo.webdatamodule"
depends_on = [
    "bionemo.core",
    "bionemo.llm",
]
