- dataset_prefix: data/metagenomics/pretraining_data_metagenomics/data_metagenomics_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.18
- dataset_prefix: data/gtdb_v220/gtdb_v220_imgpr_merged_data/data_gtdb_imgpr_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.24
- dataset_prefix: data/imgvr/pretraining_data_imgvr/data_imgvr_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.03
- dataset_prefix: data/ncrna/pretraining_data_ncrna/data_ncrna_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.02
- dataset_prefix: data/mrna/pretraining_data_mrna/data_mrna_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.09
- dataset_prefix: data/euk_windows/stitched_transcripts/pretraining_data_stiched_mrna/data_mrna_stitch_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.09
- dataset_prefix: data/euk_windows/windows_split/5kb_windows_lowercase/5kb_windows_lowercase_pretraining_data/windows_5kb_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.35
- dataset_prefix: data/promoters/pretraining_data_promoters/data_promoters_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.0003
- dataset_prefix: data/organelle/pretraining_data_organelle/data_organelle_train_text_CharLevelTokenizer_document
  dataset_split: train
  dataset_weight: 0.005
- dataset_prefix: data/metagenomics/pretraining_data_metagenomics/data_metagenomics_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.18
- dataset_prefix: data/gtdb_v220/gtdb_v220_imgpr_merged_data/data_gtdb_imgpr_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.24
- dataset_prefix: data/imgvr/pretraining_data_imgvr/data_imgvr_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.03
- dataset_prefix: data/ncrna/pretraining_data_ncrna/data_ncrna_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.02
- dataset_prefix: data/mrna/pretraining_data_mrna/data_mrna_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.09
- dataset_prefix: data/euk_windows/stitched_transcripts/pretraining_data_stiched_mrna/data_mrna_stitch_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.09
- dataset_prefix: data/euk_windows/windows_split/5kb_windows_lowercase/5kb_windows_lowercase_pretraining_data/windows_5kb_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.35
- dataset_prefix: data/promoters/pretraining_data_promoters/data_promoters_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.0003
- dataset_prefix: data/organelle/pretraining_data_organelle/data_organelle_valid_text_CharLevelTokenizer_document
  dataset_split: validation
  dataset_weight: 0.005
- dataset_prefix: data/metagenomics/pretraining_data_metagenomics/data_metagenomics_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.18
- dataset_prefix: data/gtdb_v220/gtdb_v220_imgpr_merged_data/data_gtdb_imgpr_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.24
- dataset_prefix: data/imgvr/pretraining_data_imgvr/data_imgvr_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.03
- dataset_prefix: data/ncrna/pretraining_data_ncrna/data_ncrna_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.02
- dataset_prefix: data/mrna/pretraining_data_mrna/data_mrna_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.09
- dataset_prefix: data/euk_windows/stitched_transcripts/pretraining_data_stiched_mrna/data_mrna_stitch_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.09
- dataset_prefix: data/euk_windows/windows_split/5kb_windows_lowercase/5kb_windows_lowercase_pretraining_data/windows_5kb_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.35
- dataset_prefix: data/promoters/pretraining_data_promoters/data_promoters_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.0003
- dataset_prefix: data/organelle/pretraining_data_organelle/data_organelle_test_text_CharLevelTokenizer_document
  dataset_split: test
  dataset_weight: 0.005
