name: Install internal tools Python packages & run test suite

on:
  pull_request:
    branches: [main]
    paths:
      - internal/infra-bionemo/**

jobs:
  infra-bionemo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements-dev.txt -r requirements-test.txt
      - run: pip install internal/infra-bionemo
      - run: cd internal/infra-bionemo && pytest -v --cov=infra_bionemo --cov-report=term .
